### ISSUE TITLE
Version for Kodi 19 (Matrix)

### ISSUE THREAD

**Issue by fbacher** [Razzeee/script.module.dateutil#4]
I have been using a patched addon.xml with this plugin to get it to work with Kodi 19. Are there plans to update this and put into the repo, or do you need help with this?

**Comment by razzeee** [comment]
Not sure what your asking, this is in the repo http://ftp.snt.utwente.nl/pub/software/xbmc/addons/matrix/addons.xml and it has been, for at least 1 1/2 years :)

**Comment by fbacher** [comment]
You are right! 

I did not know where the offical kodi repository was so was unaware of the latest versions of everything. I did check  at https://github.com/Razzeee/script.module.dateutil/blob/master/addon.xml and saw that the latest change was to set version to 2.8.1. 

Anyway, with your example and some digging, I found the real repository at https://mirrors.kodi.tv/addons/matrix/. I have changed my addon.xml to the latest versions of everything and now it is working.

Sorry for the fire drill!
